#!/usr/bin/perl -w
use strict;
use warnings;
use VideoLib::CGIHandler;
use VideoLib::Profile;

my $query = VideoLib::CGIHandler->new;

my $profile = VideoLib::Profile->new(request => $query->request, 'decode-content'=>0);
my $response = $profile->generate_admin_profile;
$query->send_response($response);
