#!/usr/bin/perl -w
use strict;
use warnings;
use VideoLib::CGIHandler;
use VideoLib::User;

my $query = VideoLib::CGIHandler->new;

my $user = VideoLib::User->new(request => $query->request);
my $response = $user->logout;
$query->send_response($response);
