#!/usr/bin/perl -w
use strict;
use warnings;
use VideoLib::CGIHandler;
use VideoLib::Search;

my $query = VideoLib::CGIHandler->new;

my $search = VideoLib::Search->new(request => $query->request, 'decode-content'=>0);
my $response = $search->perform_search;
$query->send_response($response);
